version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    networks: 
      - net
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db
  crud:
    container_name: crud
    build: ./service-crud
    environment:
      MONGODB_DATABASE: users
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopwd
      MONGODB_HOSTNAME: mongo-auth
    networks:
      - net
    ports:
      - 5001:5001
  auth:
    container_name: auth
    build: ./service-auth
    environment:
      MONGODB_DATABASE: users
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopwd
      MONGODB_HOSTNAME: mongo-auth
    networks:
      - net
    ports:
      - 5002:5002
networks:
  net:
volumes: 
  data: