version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    networks: 
      - net
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db
  crud:
    container_name: crud
    build: ./service-crud
    environment:
      MONGODB_DATABASE: users
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopwd
      MONGODB_HOSTNAME: db
    networks:
      - net
    ports:
      - 5001:5001
  auth:
    container_name: auth
    build: ./service-auth
    environment:
      MONGODB_DATABASE: users
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopwd
      MONGODB_HOSTNAME: db
    networks:
      - net
    ports:
      - 5002:5002
  log:
    container_name: log
    build: ./service-log
    environment:
      MONGODB_DATABASE: users
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopwd
      MONGODB_HOSTNAME: db
    networks:
      - net
    ports:
      - 5003:5003
  front:
    container_name: front
    build: ./service-front
    networks:
      - net
    ports:
      - 3000:3000
networks:
  net:
volumes: 
  data: