version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    networks: 
      - net
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db
  crud:
    container_name: crud-py
    build: ./service-crud
    environment:
      MONGODB_DATABASE: users
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopwd
      MONGODB_HOSTNAME: mongo-auth
    networks:
      - net
    ports:
      - 5000:5000
  auth:
    container_name: auth-njs
    # build: ./service-auth
    build:
      context: ./service-auth
    environment:
      NODE_ENV: production
    networks: 
      - net
    ports:
      - 3000:3000
networks:
  net:
volumes: 
  data: